require:
  - ./lib/netsoft/rubocop/cops/auth_http_positional_arguments
  - rubocop-rails
  - rubocop-performance
  - rubocop-rspec

AllCops:
  TargetRubyVersion: 2.4
  TargetRailsVersion: 5.2
  DisplayStyleGuide: true
  StyleGuideBaseURL: https://rubystyle.guide
  Exclude:
    - 'db/**/*'
    - 'coverage/**/*'
    - 'log/**/*'
    - 'public/**/*'
    - 'tmp/**/*'
    - 'spec/dummy/**/*'
    - 'vendor/**/*'
    - 'gemfiles/**/*'
    - 'node_modules/**/*'

Naming/RescuedExceptionsVariableName:
  PreferredName: ex

Naming/UncommunicativeMethodParamName:
  AllowedNames:
    - me
    - ex

Layout/AlignHash:
  EnforcedHashRocketStyle: table
  EnforcedColonStyle: table

Layout/ExtraSpacing:
  AllowForAlignment: true

Layout/IndentAssignment:
  IndentationWidth: 4

Layout/IndentFirstArrayElement:
  EnforcedStyle: consistent
  IndentationWidth: 4

Layout/IndentFirstHashElement:
  EnforcedStyle: consistent
  IndentationWidth: 4

Layout/SpaceInsideBlockBraces:
  EnforcedStyle: space
  SpaceBeforeBlockParameters: true

Layout/SpaceInsideHashLiteralBraces:
  EnforcedStyle: no_space

Lint/AmbiguousBlockAssociation:
  Exclude:
    - spec/**/*

Rails:
  Enabled: true

Rails/HttpPositionalArguments:
  Enabled: false

Rails/UnknownEnv:
  Environments:
    - production
    - staging
    - development
    - test
    - review

Rails/SkipsModelValidations:
  Whitelist:
    - touch
    - update_attribute
    - update_counters
    - increment_counter
    - decrement_counter

Netsoft/AuthHttpPositionalArguments:
  Enabled: true
  Include:
    - 'spec/controllers/**/*'

RSpec/ExpectChange:
  EnforcedStyle: block

RSpec/ImplicitSubject:
  Enabled: false

RSpec/MessageSpies:
  Enabled: false

RSpec/NamedSubject:
  Enabled: false

RSpec/NestedGroups:
  Enabled: false

RSpec/NotToNot:
  EnforcedStyle: to_not

Style/AndOr:
  EnforcedStyle: conditionals

Style/BlockDelimiters:
  EnforcedStyle: semantic
  AllowBracesOnProceduralOneLiners: true

Style/MultilineBlockChain:
  Enabled: false

Style/RescueModifier:
  Enabled: false

Style/TrailingCommaInArrayLiteral:
  EnforcedStyleForMultiline: comma

Style/TrailingCommaInHashLiteral:
  EnforcedStyleForMultiline: comma

Metrics:
  Enabled: false
