name: Run tests

on:
  workflow_call:
  workflow_dispatch:
  pull_request:

env:
  RUBYOPT: "-W:no-deprecated -W:no-experimental"

jobs:
  backend:
    name: Rubocop
    runs-on: [self-hosted, linux, x64, small]
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Install dependencies
        uses: ./.github/workflows/composite-actions/dependencies

      - name: Cache Rubocop
        uses: actions/cache@v4
        with:
          path: $HOME/.cache/rubocop_cache
          key: netsoft-rubocop-rubocop-${{ hashFiles('.rubocop.yml') }}
          restore-keys: |
            netsoft-rubocop-rubocop-${{ hashFiles('.rubocop.yml') }}
            netsoft-rubocop-rubocop-

      - name: Rubocop
        shell: bash
        run: |
          bundle exec rubocop \
            --parallel \
            --format progress
